[versions]
agp = "8.11.0"
guava = "33.4.8-android"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

